apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: docs
  annotations:
    github.com/project-slug: pats/turborepo-example
  tags:
    - website
    - nodejs
    - frontend
    - codesnoop
spec:
  type: website
  owner: pats
  lifecycle: production
  system: turborepo-example
